/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MealPlanItem, MealType } from "./components/meal-planner/meal-planner";
export { MealPlanItem, MealType } from "./components/meal-planner/meal-planner";
export namespace Components {
    interface AppModal {
        /**
          * Close when clicking the backdrop.
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Close when pressing Escape.
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Modal title.
          * @default ""
         */
        "modalTitle": string;
        /**
          * Controls whether the modal is visible.
          * @default false
         */
        "open": boolean;
    }
    interface MealPlanner {
        /**
          * Planned meals.  One recipe per date + mealType.
          * @default []
         */
        "mealPlans": MealPlanItem[];
        /**
          * Any date within the week.  The component automatically calculates Monday.
         */
        "weekStartDate": string;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default false
         */
        "hideActions": boolean;
        /**
          * @default false
         */
        "isFavorite": boolean;
        "recipe": any;
    }
    interface RecipeDemo {
    }
    interface RecipeDetail {
        "recipe": any;
    }
    interface RecipeForm {
        /**
          * @default []
         */
        "categories": CategoryOption[];
        /**
          * @default {}
         */
        "recipe": any;
    }
    interface RecipeList {
        /**
          * @default []
         */
        "favoriteIds": string[];
        /**
          * @default false
         */
        "hideActions": boolean;
        /**
          * @default 'grid'
         */
        "layout": 'grid' | 'list';
        /**
          * @default []
         */
        "recipes": any[];
    }
}
export interface AppModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppModalElement;
}
export interface MealPlannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlannerElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeDetailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeDetailElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
declare global {
    interface HTMLAppModalElementEventMap {
        "modalClose": void;
    }
    interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppModalElementEventMap>(type: K, listener: (this: HTMLAppModalElement, ev: AppModalCustomEvent<HTMLAppModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppModalElementEventMap>(type: K, listener: (this: HTMLAppModalElement, ev: AppModalCustomEvent<HTMLAppModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppModalElement: {
        prototype: HTMLAppModalElement;
        new (): HTMLAppModalElement;
    };
    interface HTMLMealPlannerElementEventMap {
        "addRecipe": {
    date: string;
    mealType: MealType;
  };
        "editRecipe": MealPlanItem;
        "deleteRecipe": MealPlanItem;
        "clearDay": string;
        "clearWeek": void;
        "previousWeek": string;
        "nextWeek": string;
        "todayClicked": string;
    }
    interface HTMLMealPlannerElement extends Components.MealPlanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlannerElementEventMap>(type: K, listener: (this: HTMLMealPlannerElement, ev: MealPlannerCustomEvent<HTMLMealPlannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlannerElementEventMap>(type: K, listener: (this: HTMLMealPlannerElement, ev: MealPlannerCustomEvent<HTMLMealPlannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlannerElement: {
        prototype: HTMLMealPlannerElement;
        new (): HTMLMealPlannerElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favorite": string;
        "open": string;
        "edit": string;
        "delete": string;
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeDemoElement extends Components.RecipeDemo, HTMLStencilElement {
    }
    var HTMLRecipeDemoElement: {
        prototype: HTMLRecipeDemoElement;
        new (): HTMLRecipeDemoElement;
    };
    interface HTMLRecipeDetailElementEventMap {
        "edit": string;
        "remove": string;
    }
    interface HTMLRecipeDetailElement extends Components.RecipeDetail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeDetailElementEventMap>(type: K, listener: (this: HTMLRecipeDetailElement, ev: RecipeDetailCustomEvent<HTMLRecipeDetailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeDetailElementEventMap>(type: K, listener: (this: HTMLRecipeDetailElement, ev: RecipeDetailCustomEvent<HTMLRecipeDetailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeDetailElement: {
        prototype: HTMLRecipeDetailElement;
        new (): HTMLRecipeDetailElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "save": any;
    }
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLRecipeListElement extends Components.RecipeList, HTMLStencilElement {
    }
    var HTMLRecipeListElement: {
        prototype: HTMLRecipeListElement;
        new (): HTMLRecipeListElement;
    };
    interface HTMLElementTagNameMap {
        "app-modal": HTMLAppModalElement;
        "meal-planner": HTMLMealPlannerElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-demo": HTMLRecipeDemoElement;
        "recipe-detail": HTMLRecipeDetailElement;
        "recipe-form": HTMLRecipeFormElement;
        "recipe-list": HTMLRecipeListElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface AppModal {
        /**
          * Close when clicking the backdrop.
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Close when pressing Escape.
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Modal title.
          * @default ""
         */
        "modalTitle"?: string;
        "onModalClose"?: (event: AppModalCustomEvent<void>) => void;
        /**
          * Controls whether the modal is visible.
          * @default false
         */
        "open"?: boolean;
    }
    interface MealPlanner {
        /**
          * Planned meals.  One recipe per date + mealType.
          * @default []
         */
        "mealPlans"?: MealPlanItem[];
        "onAddRecipe"?: (event: MealPlannerCustomEvent<{
    date: string;
    mealType: MealType;
  }>) => void;
        "onClearDay"?: (event: MealPlannerCustomEvent<string>) => void;
        "onClearWeek"?: (event: MealPlannerCustomEvent<void>) => void;
        "onDeleteRecipe"?: (event: MealPlannerCustomEvent<MealPlanItem>) => void;
        "onEditRecipe"?: (event: MealPlannerCustomEvent<MealPlanItem>) => void;
        "onNextWeek"?: (event: MealPlannerCustomEvent<string>) => void;
        "onPreviousWeek"?: (event: MealPlannerCustomEvent<string>) => void;
        "onTodayClicked"?: (event: MealPlannerCustomEvent<string>) => void;
        /**
          * Any date within the week.  The component automatically calculates Monday.
         */
        "weekStartDate": string;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default false
         */
        "hideActions"?: boolean;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        "onDelete"?: (event: RecipeCardCustomEvent<string>) => void;
        "onEdit"?: (event: RecipeCardCustomEvent<string>) => void;
        "onFavorite"?: (event: RecipeCardCustomEvent<string>) => void;
        "onOpen"?: (event: RecipeCardCustomEvent<string>) => void;
        "recipe"?: any;
    }
    interface RecipeDemo {
    }
    interface RecipeDetail {
        "onEdit"?: (event: RecipeDetailCustomEvent<string>) => void;
        "onRemove"?: (event: RecipeDetailCustomEvent<string>) => void;
        "recipe"?: any;
    }
    interface RecipeForm {
        /**
          * @default []
         */
        "categories"?: CategoryOption[];
        "onSave"?: (event: RecipeFormCustomEvent<any>) => void;
        /**
          * @default {}
         */
        "recipe"?: any;
    }
    interface RecipeList {
        /**
          * @default []
         */
        "favoriteIds"?: string[];
        /**
          * @default false
         */
        "hideActions"?: boolean;
        /**
          * @default 'grid'
         */
        "layout"?: 'grid' | 'list';
        /**
          * @default []
         */
        "recipes"?: any[];
    }

    interface AppModalAttributes {
        "open": boolean;
        "modalTitle": string;
        "closeOnBackdrop": boolean;
        "closeOnEscape": boolean;
    }
    interface MealPlannerAttributes {
        "weekStartDate": string;
    }
    interface RecipeCardAttributes {
        "recipe": string;
        "compact": boolean;
        "isFavorite": boolean;
        "hideActions": boolean;
    }
    interface RecipeDetailAttributes {
        "recipe": string;
    }
    interface RecipeFormAttributes {
        "recipe": string;
    }
    interface RecipeListAttributes {
        "layout": 'grid' | 'list';
        "hideActions": boolean;
    }

    interface IntrinsicElements {
        "app-modal": Omit<AppModal, keyof AppModalAttributes> & { [K in keyof AppModal & keyof AppModalAttributes]?: AppModal[K] } & { [K in keyof AppModal & keyof AppModalAttributes as `attr:${K}`]?: AppModalAttributes[K] } & { [K in keyof AppModal & keyof AppModalAttributes as `prop:${K}`]?: AppModal[K] };
        "meal-planner": Omit<MealPlanner, keyof MealPlannerAttributes> & { [K in keyof MealPlanner & keyof MealPlannerAttributes]?: MealPlanner[K] } & { [K in keyof MealPlanner & keyof MealPlannerAttributes as `attr:${K}`]?: MealPlannerAttributes[K] } & { [K in keyof MealPlanner & keyof MealPlannerAttributes as `prop:${K}`]?: MealPlanner[K] } & OneOf<"weekStartDate", MealPlanner["weekStartDate"], MealPlannerAttributes["weekStartDate"]>;
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-demo": RecipeDemo;
        "recipe-detail": Omit<RecipeDetail, keyof RecipeDetailAttributes> & { [K in keyof RecipeDetail & keyof RecipeDetailAttributes]?: RecipeDetail[K] } & { [K in keyof RecipeDetail & keyof RecipeDetailAttributes as `attr:${K}`]?: RecipeDetailAttributes[K] } & { [K in keyof RecipeDetail & keyof RecipeDetailAttributes as `prop:${K}`]?: RecipeDetail[K] };
        "recipe-form": Omit<RecipeForm, keyof RecipeFormAttributes> & { [K in keyof RecipeForm & keyof RecipeFormAttributes]?: RecipeForm[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `attr:${K}`]?: RecipeFormAttributes[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `prop:${K}`]?: RecipeForm[K] };
        "recipe-list": Omit<RecipeList, keyof RecipeListAttributes> & { [K in keyof RecipeList & keyof RecipeListAttributes]?: RecipeList[K] } & { [K in keyof RecipeList & keyof RecipeListAttributes as `attr:${K}`]?: RecipeListAttributes[K] } & { [K in keyof RecipeList & keyof RecipeListAttributes as `prop:${K}`]?: RecipeList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-modal": LocalJSX.IntrinsicElements["app-modal"] & JSXBase.HTMLAttributes<HTMLAppModalElement>;
            "meal-planner": LocalJSX.IntrinsicElements["meal-planner"] & JSXBase.HTMLAttributes<HTMLMealPlannerElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-demo": LocalJSX.IntrinsicElements["recipe-demo"] & JSXBase.HTMLAttributes<HTMLRecipeDemoElement>;
            "recipe-detail": LocalJSX.IntrinsicElements["recipe-detail"] & JSXBase.HTMLAttributes<HTMLRecipeDetailElement>;
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            "recipe-list": LocalJSX.IntrinsicElements["recipe-list"] & JSXBase.HTMLAttributes<HTMLRecipeListElement>;
        }
    }
}
