/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MealPlanner {
        /**
          * @default {}
         */
        "plan": any;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default false
         */
        "isFavorite": boolean;
        "recipe": any;
    }
    interface RecipeDemo {
    }
    interface RecipeDetail {
        "recipe": any;
    }
    interface RecipeForm {
        /**
          * @default []
         */
        "categories": CategoryOption[];
        /**
          * @default {}
         */
        "recipe": any;
    }
    interface RecipeList {
        /**
          * @default []
         */
        "favoriteIds": string[];
        /**
          * @default 'grid'
         */
        "layout": 'grid' | 'list';
        /**
          * @default []
         */
        "recipes": any[];
    }
}
export interface MealPlannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlannerElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeDetailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeDetailElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
declare global {
    interface HTMLMealPlannerElementEventMap {
        "planChange": any;
    }
    interface HTMLMealPlannerElement extends Components.MealPlanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlannerElementEventMap>(type: K, listener: (this: HTMLMealPlannerElement, ev: MealPlannerCustomEvent<HTMLMealPlannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlannerElementEventMap>(type: K, listener: (this: HTMLMealPlannerElement, ev: MealPlannerCustomEvent<HTMLMealPlannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlannerElement: {
        prototype: HTMLMealPlannerElement;
        new (): HTMLMealPlannerElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favorite": string;
        "open": string;
        "edit": string;
        "delete": string;
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeDemoElement extends Components.RecipeDemo, HTMLStencilElement {
    }
    var HTMLRecipeDemoElement: {
        prototype: HTMLRecipeDemoElement;
        new (): HTMLRecipeDemoElement;
    };
    interface HTMLRecipeDetailElementEventMap {
        "edit": string;
        "remove": string;
    }
    interface HTMLRecipeDetailElement extends Components.RecipeDetail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeDetailElementEventMap>(type: K, listener: (this: HTMLRecipeDetailElement, ev: RecipeDetailCustomEvent<HTMLRecipeDetailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeDetailElementEventMap>(type: K, listener: (this: HTMLRecipeDetailElement, ev: RecipeDetailCustomEvent<HTMLRecipeDetailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeDetailElement: {
        prototype: HTMLRecipeDetailElement;
        new (): HTMLRecipeDetailElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "save": any;
    }
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLRecipeListElement extends Components.RecipeList, HTMLStencilElement {
    }
    var HTMLRecipeListElement: {
        prototype: HTMLRecipeListElement;
        new (): HTMLRecipeListElement;
    };
    interface HTMLElementTagNameMap {
        "meal-planner": HTMLMealPlannerElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-demo": HTMLRecipeDemoElement;
        "recipe-detail": HTMLRecipeDetailElement;
        "recipe-form": HTMLRecipeFormElement;
        "recipe-list": HTMLRecipeListElement;
    }
}
declare namespace LocalJSX {
    interface MealPlanner {
        "onPlanChange"?: (event: MealPlannerCustomEvent<any>) => void;
        /**
          * @default {}
         */
        "plan"?: any;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        "onDelete"?: (event: RecipeCardCustomEvent<string>) => void;
        "onEdit"?: (event: RecipeCardCustomEvent<string>) => void;
        "onFavorite"?: (event: RecipeCardCustomEvent<string>) => void;
        "onOpen"?: (event: RecipeCardCustomEvent<string>) => void;
        "recipe"?: any;
    }
    interface RecipeDemo {
    }
    interface RecipeDetail {
        "onEdit"?: (event: RecipeDetailCustomEvent<string>) => void;
        "onRemove"?: (event: RecipeDetailCustomEvent<string>) => void;
        "recipe"?: any;
    }
    interface RecipeForm {
        /**
          * @default []
         */
        "categories"?: CategoryOption[];
        "onSave"?: (event: RecipeFormCustomEvent<any>) => void;
        /**
          * @default {}
         */
        "recipe"?: any;
    }
    interface RecipeList {
        /**
          * @default []
         */
        "favoriteIds"?: string[];
        /**
          * @default 'grid'
         */
        "layout"?: 'grid' | 'list';
        /**
          * @default []
         */
        "recipes"?: any[];
    }

    interface MealPlannerAttributes {
        "plan": string;
    }
    interface RecipeCardAttributes {
        "recipe": string;
        "compact": boolean;
        "isFavorite": boolean;
    }
    interface RecipeDetailAttributes {
        "recipe": string;
    }
    interface RecipeFormAttributes {
        "recipe": string;
    }
    interface RecipeListAttributes {
        "layout": 'grid' | 'list';
    }

    interface IntrinsicElements {
        "meal-planner": Omit<MealPlanner, keyof MealPlannerAttributes> & { [K in keyof MealPlanner & keyof MealPlannerAttributes]?: MealPlanner[K] } & { [K in keyof MealPlanner & keyof MealPlannerAttributes as `attr:${K}`]?: MealPlannerAttributes[K] } & { [K in keyof MealPlanner & keyof MealPlannerAttributes as `prop:${K}`]?: MealPlanner[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-demo": RecipeDemo;
        "recipe-detail": Omit<RecipeDetail, keyof RecipeDetailAttributes> & { [K in keyof RecipeDetail & keyof RecipeDetailAttributes]?: RecipeDetail[K] } & { [K in keyof RecipeDetail & keyof RecipeDetailAttributes as `attr:${K}`]?: RecipeDetailAttributes[K] } & { [K in keyof RecipeDetail & keyof RecipeDetailAttributes as `prop:${K}`]?: RecipeDetail[K] };
        "recipe-form": Omit<RecipeForm, keyof RecipeFormAttributes> & { [K in keyof RecipeForm & keyof RecipeFormAttributes]?: RecipeForm[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `attr:${K}`]?: RecipeFormAttributes[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `prop:${K}`]?: RecipeForm[K] };
        "recipe-list": Omit<RecipeList, keyof RecipeListAttributes> & { [K in keyof RecipeList & keyof RecipeListAttributes]?: RecipeList[K] } & { [K in keyof RecipeList & keyof RecipeListAttributes as `attr:${K}`]?: RecipeListAttributes[K] } & { [K in keyof RecipeList & keyof RecipeListAttributes as `prop:${K}`]?: RecipeList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "meal-planner": LocalJSX.IntrinsicElements["meal-planner"] & JSXBase.HTMLAttributes<HTMLMealPlannerElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-demo": LocalJSX.IntrinsicElements["recipe-demo"] & JSXBase.HTMLAttributes<HTMLRecipeDemoElement>;
            "recipe-detail": LocalJSX.IntrinsicElements["recipe-detail"] & JSXBase.HTMLAttributes<HTMLRecipeDetailElement>;
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            "recipe-list": LocalJSX.IntrinsicElements["recipe-list"] & JSXBase.HTMLAttributes<HTMLRecipeListElement>;
        }
    }
}
